// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC15ysvvRT2ZhJf3JlwfZ80bEBu_TnAzuA',
    appId: '1:227345902510:web:5c8259b93b753aaab3763f',
    messagingSenderId: '227345902510',
    projectId: 'testing-5f2f1',
    authDomain: 'testing-5f2f1.firebaseapp.com',
    storageBucket: 'testing-5f2f1.appspot.com',
    measurementId: 'G-GSEYERB578',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVi56j2TcRuQE8rWaDEHq39e2pw_Y0XjQ',
    appId: '1:227345902510:android:4e83bcb96d6d9468b3763f',
    messagingSenderId: '227345902510',
    projectId: 'testing-5f2f1',
    storageBucket: 'testing-5f2f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnxWMsaoBLLG6zV9fHOfEsuyFG5wYE4DI',
    appId: '1:227345902510:ios:3e739cd1c13c36d4b3763f',
    messagingSenderId: '227345902510',
    projectId: 'testing-5f2f1',
    storageBucket: 'testing-5f2f1.appspot.com',
    iosClientId: '227345902510-nfhemekb616eekrf8o5qbgm9vbtd5hs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnxWMsaoBLLG6zV9fHOfEsuyFG5wYE4DI',
    appId: '1:227345902510:ios:0dd0b325f830f268b3763f',
    messagingSenderId: '227345902510',
    projectId: 'testing-5f2f1',
    storageBucket: 'testing-5f2f1.appspot.com',
    iosBundleId: 'com.example.testing.RunnerTests',
  );
}
